# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_dmvn <- function(x, Sigma) {
    .Call('_mpsBART5_log_dmvn', PACKAGE = 'mpsBART5', x, Sigma)
}

sum_exclude_col <- function(mat, exclude_int) {
    .Call('_mpsBART5_sum_exclude_col', PACKAGE = 'mpsBART5', mat, exclude_int)
}

bspline <- function(x, x_obs) {
    .Call('_mpsBART5_bspline', PACKAGE = 'mpsBART5', x, x_obs)
}

sbart <- function(x_train, y_train, x_test, B_train, B_test, n_tree, n_mcmc, n_burn, tau, mu, tau_mu, tau_b, tau_b_intercept, alpha, beta, a_tau, d_tau, nu, delta, a_delta, d_delta, a_tau_b, d_tau_b, p_sample, p_sample_levels, intercept_model, stump) {
    .Call('_mpsBART5_sbart', PACKAGE = 'mpsBART5', x_train, y_train, x_test, B_train, B_test, n_tree, n_mcmc, n_burn, tau, mu, tau_mu, tau_b, tau_b_intercept, alpha, beta, a_tau, d_tau, nu, delta, a_delta, d_delta, a_tau_b, d_tau_b, p_sample, p_sample_levels, intercept_model, stump)
}

mat_init <- function(n) {
    .Call('_mpsBART5_mat_init', PACKAGE = 'mpsBART5', n)
}

vec_init <- function(n) {
    .Call('_mpsBART5_vec_init', PACKAGE = 'mpsBART5', n)
}

std_inv <- function(A, diag) {
    .Call('_mpsBART5_std_inv', PACKAGE = 'mpsBART5', A, diag)
}

std_pinv <- function(A, diag) {
    .Call('_mpsBART5_std_pinv', PACKAGE = 'mpsBART5', A, diag)
}

faster_simple_std_inv <- function(A, diag) {
    .Call('_mpsBART5_faster_simple_std_inv', PACKAGE = 'mpsBART5', A, diag)
}

faster_std_inv <- function(A, diag) {
    .Call('_mpsBART5_faster_std_inv', PACKAGE = 'mpsBART5', A, diag)
}

rMVN2 <- function(b, Q) {
    .Call('_mpsBART5_rMVN2', PACKAGE = 'mpsBART5', b, Q)
}

rMVNslow <- function(b, Q) {
    .Call('_mpsBART5_rMVNslow', PACKAGE = 'mpsBART5', b, Q)
}

matrix_mat <- function(array) {
    .Call('_mpsBART5_matrix_mat', PACKAGE = 'mpsBART5', array)
}

rand_unif <- function() {
    .Call('_mpsBART5_rand_unif', PACKAGE = 'mpsBART5')
}

